language: node_js

node_js: stable

branches:
  only:
  - master

cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    - $HOME/.npm

before_install:
- git config --global user.name "Andrew Wong"
- git config --global user.email "argsno@gmail.com"
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- npm install -g hexo-cli

install:
- yarn

script:
- hexo clean
- hexo generate

after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git push --quiet --force https://$REPO_TOKEN@github.com/argsno/argsno.github.io.git
  master